### PR TITLE
Remove the Analytics Api.

### PR DESCRIPTION
**Pull request by derekclee**
Nobody should be using it and we want everyone to use the new kale api once it is ready.

### CODE REVIEW

**Comment by derekclee** [comment]
screenshot 2015-12-09 14 29 38

Local screen shot. Analytics used to be between Custom Fields and Reminder.

@kapost/insights @brandonc  Ready for review.  Not sure how this is deployed.

**Comment by brandonc** [comment]
:+1:

**Comment by derekclee** [comment]
@brandonc How does one deploy this app? Thanks.

**Comment by brandonc** [comment]
push to heroku git

**Comment by brandonc** [comment]
there's no environment management in this repo

**Pull request merged**
